##
## Test Suites
##

    modified.files.includes[relevant][layout-content-page-editor-web-rule]=**

    relevant.rule.names=\
        layout-content-page-editor-web-rule

    test.batch.names[relevant][layout-content-page-editor-web-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit,\
        playwright-js-tomcat90-mysql57

    modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][layout-content-page-editor-web-rule]=\
        apps/layout/layout-content-page-editor-web/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][layout-content-page-editor-web-rule]=\
        apps/layout/layout-content-page-editor-web/**/*Test.java

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][layout-content-page-editor-web-rule]}

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][layout-content-page-editor-web-rule]=layout-content-page-editor-web

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][layout-content-page-editor-web-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.main.component.name ~ "Content Page Templates") OR \
            (testray.main.component.name ~ "Content Pages") OR \
            (testray.main.component.name ~ "Display Page Templates") OR \
            (testray.main.component.name ~ "Fragment Administration") OR \
            (testray.main.component.name ~ "Master Pages") OR \
            (testray.main.component.name ~ "Page Administration") OR \
            (testray.main.component.name ~ "Page Editor")\
        )

##
## Testray
##

    testray.main.component.name=Content Pages