##
## Test Suites
##

    modified.files.includes[relevant][osgi-bundle-builder-rule]=**

    relevant.rule.names=\
        osgi-bundle-builder-rule

    test.batch.names[relevant][osgi-bundle-builder-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][osgi-bundle-builder-rule]=\
        util/osgi-bundle-builder/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][osgi-bundle-builder-rule]=\
        util/osgi-bundle-builder/**/*Test.java