##
## Test Suites
##

    modified.files.includes[relevant][portlet-configuration-css-web-rule]=**

    relevant.rule.names=\
        portlet-configuration-css-web-rule

    test.batch.names[relevant][portlet-configuration-css-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][portlet-configuration-css-web-rule]=portlet-configuration-css-web

##
## Testray
##

    testray.main.component.name=Widget Configuration