##
## Test Suites
##

    modified.files.includes[relevant][site-initializer-rule]=**

    relevant.rule.names=\
        site-initializer-rule

    test.batch.names[relevant][site-initializer-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][site-initializer-rule]=\
        apps/site-initializer/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][site-initializer-rule]=\
        apps/site-initializer/**/*Test.java

##
## Testray
##

    testray.main.component.name=Site Initializer Extender