##
## Test Suites
##

    modified.files.includes[relevant][release-util-rule]=**

    relevant.rule.names=\
        release-util-rule

    test.batch.names[relevant][release-util-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][release-util-rule]=\
        util/release-util/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][release-util-rule]=\
        util/release-util/**/*Test.java