##
## Test Suites
##

    modified.files.includes[relevant][feature-flag-web-rule]=**

    relevant.rule.names=\
        feature-flag-web-rule

    test.batch.names[relevant][feature-flag-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][feature-flag-web-rule]=feature-flag-web