##
## Test Suites
##

    modified.files.includes[relevant][saml-web-rule]=**

    relevant.rule.names=\
        saml-web-rule

    test.batch.names[relevant][saml-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][saml-web-rule]=saml-web