##
## Test Suites
##

    modified.files.includes[relevant][dispatch-web-rule]=**

    relevant.rule.names=\
        dispatch-web-rule

    test.batch.names[relevant][dispatch-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][dispatch-web-rule]=dispatch-web