##
## Test Suites
##

    modified.files.includes[relevant][message-boards-rule]=**

    relevant.rule.names=\
        message-boards-rule

    test.batch.names[relevant][message-boards-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit,\
        playwright-js-tomcat90-mysql57

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][message-boards-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][message-boards-rule]=\
        apps/message-boards/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][message-boards-rule]=\
        apps/message-boards/**/*Test.java

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][message-boards-rule]=message-boards-web

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][message-boards-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Message Boards") OR \
            (testray.main.component.name ~ "Message Boards")\
        )

##
## Testray
##

    testray.main.component.name=Message Boards