##
## Test Suites
##

    modified.files.includes[relevant][portal-workflow-kaleo-designer-web-rule]=**

    relevant.rule.names=\
        portal-workflow-kaleo-designer-web-rule

    test.batch.names[relevant][portal-workflow-kaleo-designer-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][portal-workflow-kaleo-designer-web-rule]=portal-workflow-kaleo-designer-web