##
## Test Suites
##

    modified.files.includes[relevant][archived-rule]=**

    relevant.rule.names=\
        archived-rule

    test.batch.names[relevant][archived-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][archived-rule]=\
        apps/archived/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][archived-rule]=\
        apps/archived/**/*Test.java

##
## Testray
##

    testray.main.component.name=Archived Apps