##
## Test Suites
##

    modified.files.includes[relevant][ai-creator-rule]=**

    relevant.rule.names=\
        ai-creator-rule

    test.batch.names[relevant][ai-creator-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][ai-creator-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][ai-creator-rule]=\
        apps/ai-creator/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][ai-creator-rule]=\
        apps/ai-creator/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][ai-creator-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "AI-Creator")

##
## Testray
##

    testray.main.component.name=AI-Creator