##
## Test Suites
##

    modified.files.includes[relevant][portal-workflow-rule]=**

    relevant.rule.names=\
        portal-workflow-rule

    test.batch.names[relevant][portal-workflow-rule]=\
        functional-tomcat90-mysql57,\
        functional-upgrade-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][portal-workflow-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][portal-workflow-rule]=\
        apps/portal-workflow/**/*Test.java,\
        dxp/apps/portal-workflow/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-workflow-rule]=\
        apps/portal-workflow/**/*Test.java,\
        dxp/apps/portal-workflow/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][portal-workflow-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Workflow") OR \
            (testray.main.component.name ~ "Kaleo Designer") OR \
            (testray.main.component.name ~ "Workflow")\
        )

    test.batch.run.property.query[functional-upgrade-tomcat*-mysql*][relevant][portal-workflow-rule]=\
        (testray.main.component.name == "Upgrades Workflow")

##
## Testray
##

    testray.main.component.name=Workflow Metrics