##
## Test Suites
##

    modified.files.includes[relevant][repository-rule]=**

    relevant.rule.names=\
        repository-rule

    test.batch.names[relevant][repository-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][repository-rule]=\
        apps/repository/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][repository-rule]=\
        apps/repository/**/*Test.java

##
## Testray
##

    testray.main.component.name=Document Management