##
## Test Suites
##

    modified.files.includes[relevant][frontend-theme-rule]=**

    relevant.rule.names=\
        frontend-theme-rule

    test.batch.names[relevant][frontend-theme-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][frontend-theme-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][frontend-theme-rule]=\
        dxp/apps/frontend-theme/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][frontend-theme-rule]=\
        dxp/apps/frontend-theme/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][frontend-theme-rule]=\
        (portal.acceptance == true) AND \
        (testray.component.names ~ "Theme")

##
## Testray
##

    testray.main.component.name=Theme