##
## Test Suites
##

    modified.files.includes[relevant][batch-engine-rule]=**

    relevant.rule.names=\
        batch-engine-rule

    test.batch.names[relevant][batch-engine-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][batch-engine-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][batch-engine-rule]=\
        apps/batch-engine/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][batch-engine-rule]=\
        apps/batch-engine/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][batch-engine-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name == "Headless Batch Engine API")

##
## Testray
##

    testray.main.component.name=Headless Batch Engine API