##
## Test Suites
##

    modified.files.includes[relevant][website-rule]=**

    relevant.rule.names=\
        website-rule

    test.batch.names[relevant][website-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][website-rule]=\
        apps/website/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][website-rule]=\
        apps/website/**/*Test.java

##
## Testray
##

    testray.main.component.name=Personal Data