##
## Test Suites
##

    modified.files.includes[relevant][portal-transaction-rule]=**

    relevant.rule.names=\
        portal-transaction-rule

    test.batch.names[relevant][portal-transaction-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][portal-transaction-rule]=\
        apps/portal-transaction/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-transaction-rule]=\
        apps/portal-transaction/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services