##
## Test Suites
##

    modified.files.includes[relevant][layout-set-prototype-web-rule]=**

    relevant.rule.names=\
        layout-set-prototype-web-rule

    test.batch.names[relevant][layout-set-prototype-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][layout-set-prototype-web-rule]=layout-set-prototype-web