##
## Test Suites
##

    modified.files.includes[relevant][portal-tools-db-support-rule]=**

    relevant.rule.names=\
        portal-tools-db-support-rule

    test.batch.names[relevant][portal-tools-db-support-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][portal-tools-db-support-rule]=\
        util/portal-tools-db-support/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-tools-db-support-rule]=\
        util/portal-tools-db-support/**/*Test.java