##
## Test Suites
##

    modified.files.includes[relevant][bean-portlet-rule]=**

    relevant.rule.names=\
        bean-portlet-rule

    test.batch.names[relevant][bean-portlet-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][bean-portlet-rule]=\
        apps/bean-portlet/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][bean-portlet-rule]=\
        apps/bean-portlet/**/*Test.java

##
## Testray
##

    testray.main.component.name=Bean Portlet