##
## Test Suites
##

    modified.files.includes[relevant][data-cleanup-rule]=**

    relevant.rule.names=\
        data-cleanup-rule

    test.batch.names[relevant][data-cleanup-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][data-cleanup-rule]=\
        apps/data-cleanup/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][data-cleanup-rule]=\
        apps/data-cleanup/**/*Test.java

##
## Testray
##

    testray.main.component.name=Data Cleanup