##
## Test Suites
##

    modified.files.includes[relevant][antivirus-rule]=**

    relevant.rule.names=\
        antivirus-rule

    test.batch.names[relevant][antivirus-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][antivirus-rule]=\
        dxp/apps/antivirus/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][antivirus-rule]=\
        dxp/apps/antivirus/**/*Test.java

##
## Testray
##

    testray.main.component.name=Antivirus