##
## Test Suites
##

    modified.files.includes[relevant][salesforce-connector-rule]=**

    relevant.rule.names=\
        salesforce-connector-rule

    test.batch.names[relevant][salesforce-connector-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][salesforce-connector-rule]=\
        dxp/apps/salesforce-connector/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][salesforce-connector-rule]=\
        dxp/apps/salesforce-connector/**/*Test.java

##
## Testray
##

    testray.main.component.name=Commerce