##
## Test Suites
##

    modified.files.includes[relevant][websocket-rule]=**

    relevant.rule.names=\
        websocket-rule

    test.batch.names[relevant][websocket-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][websocket-rule]=\
        apps/websocket/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][websocket-rule]=\
        apps/websocket/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services