##
## Test Suites
##

    modified.files.includes[relevant][external-reference-rule]=**

    relevant.rule.names=\
        external-reference-rule

    test.batch.names[relevant][external-reference-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][external-reference-rule]=\
        apps/external-reference/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][external-reference-rule]=\
        apps/external-reference/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services