##
## Test Suites
##

    modified.files.includes[relevant][asset-browser-web-rule]=**

    relevant.rule.names=\
        asset-browser-web-rule

    test.batch.names[relevant][asset-browser-web-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][asset-browser-web-rule]=\
        **/asset-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-browser-web-rule]=\
        **/asset-test/**/*Test.java