##
## Test Suites
##

    modified.files.includes[relevant][roles-rule]=**

    relevant.rule.names=\
        roles-rule

    test.batch.names[relevant][roles-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][roles-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][roles-rule]=\
        apps/roles/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][roles-rule]=\
        apps/roles/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][roles-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Roles") OR \
            (testray.main.component.name ~ "Roles")\
        )

##
## Testray
##

    testray.main.component.name=Roles