##
## Test Suites
##

    modified.files.includes[relevant][project-templates-rule]=**

    relevant.rule.names=\
        project-templates-rule

    test.batch.names[relevant][project-templates-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][project-templates-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][project-templates-rule]=\
        sdk/project-templates/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][project-templates-rule]=\
        sdk/project-templates/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][project-templates-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Project Templates") OR \
            (testray.main.component.name ~ "Project Templates")\
        )

##
## Testray
##

    testray.main.component.name=Project Templates