##
## Test Suites
##

    modified.files.includes[relevant][social-rule]=**

    relevant.rule.names=\
        social-rule

    test.batch.names[relevant][social-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][social-rule]=\
        apps/social/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][social-rule]=\
        apps/social/**/*Test.java

##
## Testray
##

    testray.main.component.name=Social Bookmarks