##
## Test Suites
##

    modified.files.includes[relevant][sharepoint-rest-rule]=**

    relevant.rule.names=\
        sharepoint-rest-rule

    test.batch.names[relevant][sharepoint-rest-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][sharepoint-rest-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][sharepoint-rest-rule]=\
        dxp/apps/sharepoint-rest/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][sharepoint-rest-rule]=\
        dxp/apps/sharepoint-rest/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][sharepoint-rest-rule]=\
        (osgi.modules.includes ~ "sharepoint-rest") AND \
        (portal.acceptance == true)

##
## Testray
##

    testray.main.component.name=External Document Repositories