##
## Test Suites
##

    modified.files.includes[relevant][frontend-token-rule]=**

    relevant.rule.names=\
        frontend-token-rule

    test.batch.names[relevant][frontend-token-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][frontend-token-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][frontend-token-rule]=\
        apps/frontend-token/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][frontend-token-rule]=\
        apps/frontend-token/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][frontend-token-rule]=\
        (portal.acceptance == true) AND \
        (testray.component.names == "Frontend Token")

##
## Testray
##

    testray.main.component.name=User Interface