##
## Test Suites
##

    modified.files.includes[relevant][headless-batch-engine-rule]=**

    relevant.rule.names=\
        headless-batch-engine-rule

    test.batch.names[relevant][headless-batch-engine-rule]=\
        functional-tomcat90-mysql57

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][headless-batch-engine-rule]}

    #
    # Relevant
    #

    test.batch.class.names.includes[relevant][headless-batch-engine-rule]=\
        **/headless-batch-engine/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][headless-batch-engine-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name == "Headless Batch Engine API")

##
## Testray
##

testray.main.component.name=Headless Batch Engine API