##
## Test Suites
##

    modified.files.includes[relevant][roles-admin-web-rule]=**

    relevant.rule.names=\
        roles-admin-web-rule

    test.batch.names[relevant][roles-admin-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][roles-admin-web-rule]=roles-admin-web