##
## Test Suites
##

    modified.files.includes[relevant][asset-link-service-rule]=**

    relevant.rule.names=\
        asset-link-service-rule

    test.batch.names[relevant][asset-link-service-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][asset-link-service-rule]=\
        **/asset-link-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-link-service-rule]=\
        **/asset-link-test/**/*Test.java