##
## Test Suites
##

    modified.files.includes[relevant][mulesoft-rule]=**

    relevant.rule.names=\
        mulesoft-rule

    test.batch.names[relevant][mulesoft-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][mulesoft-rule]=\
        core/mulesoft/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][mulesoft-rule]=\
        core/mulesoft/**/*Test.java