##
## Test Suites
##

    modified.files.includes[relevant][plugins-admin-rule]=**

    relevant.rule.names=\
        plugins-admin-rule

    test.batch.names[relevant][plugins-admin-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][plugins-admin-rule]=\
        apps/plugins-admin/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][plugins-admin-rule]=\
        apps/plugins-admin/**/*Test.java

##
## Testray
##

    testray.main.component.name=Components Admin