##
## Test Suites
##

    modified.files.includes[relevant][users-admin-rule]=**

    relevant.rule.names=\
        users-admin-rule

    test.batch.names[relevant][users-admin-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][users-admin-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][users-admin-rule]=\
        apps/users-admin/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][users-admin-rule]=\
        apps/users-admin/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][users-admin-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Users and Organizations") OR \
            (testray.main.component.name ~ "Users and Organizations")\
        )

##
## Testray
##

    testray.main.component.name=Users and Organizations