##
## Test Suites
##

    modified.files.includes[relevant][release-feature-flag-rule]=**

    relevant.rule.names=\
        release-feature-flag-rule

    test.batch.names[relevant][release-feature-flag-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][release-feature-flag-rule]=\
        apps/release-feature-flag/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][release-feature-flag-rule]=\
        apps/release-feature-flag/**/*Test.java

##
## Testray
##

    testray.main.component.name=Feature Flags