##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][wiki-service-rule]=\
        (testray.component.names == "Wiki") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    modified.files.includes[relevant][wiki-service-rule]=**

    relevant.rule.names=\
        wiki-service-rule

    test.batch.names[relevant][wiki-service-rule]=\
        functional-upgrade-tomcat90-mysql57

##
## Testray
##

    testray.main.component.name=Wiki