##
## Test Suites
##

    modified.files.includes[relevant][util-rule]=**

    relevant.rule.names=\
        util-rule

    test.batch.names[relevant][util-rule]=\
        functional-tomcat90-mysql57

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][util-rule]=\
        (testray.main.component.name == "Locale")