##
## Test Suites
##

    modified.files.includes[relevant][css-builder-rule]=**

    relevant.rule.names=\
        css-builder-rule

    test.batch.names[relevant][css-builder-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][css-builder-rule]=\
        util/css-builder/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][css-builder-rule]=\
        util/css-builder/**/*Test.java

##
## Testray
##

    testray.main.component.name=Dev Tools