apiDir: ../calendar-collab-rest-api/src/main/java
apiPackagePath: com.liferay.calendar.collab.rest
application:
    baseURI: /calendar-collab
    className: CalendarCollabRESTApplication
    name: Liferay.Calendar.Collab.REST
author: Liferay
compatibilityVersion: 13
forcePredictableOperationId: true
generateOpenAPI: false
javaEEPackage: jakarta


