##
## Test Suites
##

    modified.files.includes[relevant][layout-taglib-rule]=**

    relevant.rule.names=\
        layout-taglib-rule

    test.batch.names[relevant][layout-taglib-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][layout-taglib-rule]=layout-taglib

##
## Testray
##

    testray.main.component.name=Content Pages