##
## Test Suites
##

    modified.files.includes[relevant][image-uploader-rule]=**

    relevant.rule.names=\
        image-uploader-rule

    test.batch.names[relevant][image-uploader-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][image-uploader-rule]=\
        apps/image-uploader/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][image-uploader-rule]=\
        apps/image-uploader/**/*Test.java

##
## Testray
##

    testray.main.component.name=Image Uploader