##
## Test Suites
##

    modified.files.includes[relevant][map-rule]=**

    relevant.rule.names=\
        map-rule

    test.batch.names[relevant][map-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][map-rule]=\
        apps/map/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][map-rule]=\
        apps/map/**/*Test.java

##
## Testray
##

    testray.main.component.name=Maps