##
## Test Suites
##

    modified.files.includes[relevant][lang-sanitizer-rule]=**

    relevant.rule.names=\
        lang-sanitizer-rule

    test.batch.names[relevant][lang-sanitizer-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][lang-sanitizer-rule]=\
        util/lang-sanitizer/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][lang-sanitizer-rule]=\
        util/lang-sanitizer/**/*Test.java