##
## Test Suites
##

    modified.files.includes[relevant][headless-form-rule]=**

    relevant.rule.names=\
        headless-form-rule

    test.batch.names[relevant][headless-form-rule]=\
        functional-tomcat90-mysql57

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][headless-form-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][headless-form-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Forms")

##
## Testray
##

testray.main.component.name=Forms