##
## Test Suites
##

    modified.files.includes[relevant][enterprise-product-notification-rule]=**

    relevant.rule.names=\
        enterprise-product-notification-rule

    test.batch.names[relevant][enterprise-product-notification-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][enterprise-product-notification-rule]=\
        dxp/apps/enterprise-product-notification/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][enterprise-product-notification-rule]=\
        dxp/apps/enterprise-product-notification/**/*Test.java

##
## Testray
##

    testray.main.component.name=Notification