##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][blogs-recent-bloggers-web-rule]=\
        (testray.component.names == "Blogs") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    modified.files.includes[relevant][blogs-recent-bloggers-web-rule]=**

    relevant.rule.names=\
        blogs-recent-bloggers-web-rule

    test.batch.names[relevant][blogs-recent-bloggers-web-rule]=\
        functional-upgrade-tomcat90-mysql57

##
## Testray
##

    testray.main.component.name=Blogs