##
## Test Suites
##

    modified.files.includes[relevant][site-admin-web-rule]=**

    relevant.rule.names=\
        site-admin-web-rule

    test.batch.names[relevant][site-admin-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][site-admin-web-rule]=site-admin-web