##
## Test Suites
##

    modified.files.includes[relevant][microsoft-translator-rule]=**

    relevant.rule.names=\
        microsoft-translator-rule

    test.batch.names[relevant][microsoft-translator-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][microsoft-translator-rule]=\
        apps/microsoft-translator/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][microsoft-translator-rule]=\
        apps/microsoft-translator/**/*Test.java

##
## Testray
##

    testray.main.component.name=Translations Management