##
## Test Suites
##

    modified.files.includes[relevant][cookies-banner-web-rule]=**

    relevant.rule.names=\
        cookies-banner-web-rule

    test.batch.names[relevant][cookies-banner-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][cookies-banner-web-rule]=cookies-banner-web