##
## Test Suites
##

    modified.files.includes[relevant][cookies-rule]=**

    relevant.rule.names=\
        cookies-rule

    test.batch.names[relevant][cookies-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][cookies-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][cookies-rule]=\
        apps/cookies/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][cookies-rule]=\
        apps/cookies/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][cookies-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Cookies")

##
## Testray
##

    testray.main.component.name=Cookies