##
## Test Suites
##

    modified.files.includes[relevant][headless-builder-impl-rule]=**

    relevant.rule.names=\
        headless-builder-impl-rule

    test.batch.names[relevant][headless-builder-impl-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][headless-builder-impl-rule]=headless-builder-impl