##
## Test Suites
##

    modified.files.includes[relevant][portal-instances-rule]=**

    relevant.rule.names=\
        portal-instances-rule

    test.batch.names[relevant][portal-instances-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][portal-instances-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][portal-instances-rule]=\
        apps/portal-instances/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-instances-rule]=\
        apps/portal-instances/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][portal-instances-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Virtual Instances") OR \
            (testray.main.component.name ~ "Virtual Instances")\
        )

##
## Testray
##

    testray.main.component.name=Virtual Instances