##
## Test Suites
##

    modified.files.includes[relevant][osb-rule]=**

    relevant.rule.names=\
        osb-rule

    test.batch.names[relevant][osb-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][osb-rule]=\
        dxp/apps/osb/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][osb-rule]=\
        dxp/apps/osb/**/*Test.java