##
## Test Suites
##

    modified.files.includes[relevant][expando-rule]=**

    relevant.rule.names=\
        expando-rule

    test.batch.names[relevant][expando-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][expando-rule]=\
        apps/expando/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][expando-rule]=\
        apps/expando/**/*Test.java

##
## Testray
##

    testray.main.component.name=Custom Fields