##
## Test Suites
##

    modified.files.includes[relevant][site-initializer-team-extranet-rule]=**

    relevant.rule.names=\
        site-initializer-team-extranet-rule

    test.batch.names[relevant][site-initializer-team-extranet-rule]=\
        functional-tomcat90-mysql57

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][site-initializer-team-extranet-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][site-initializer-team-extranet-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Team Extranet") OR \
            (testray.main.component.name ~ "Team Extranet")\
        )