##
## Test Suites
##

    modified.files.includes[relevant][click-to-chat-rule]=**

    relevant.rule.names=\
        click-to-chat-rule

    test.batch.names[relevant][click-to-chat-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][click-to-chat-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][click-to-chat-rule]=\
        apps/click-to-chat/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][click-to-chat-rule]=\
        apps/click-to-chat/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][click-to-chat-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Click to Chat") OR \
            (testray.main.component.name ~ "Click to Chat")\
        )

##
## Testray
##

    testray.main.component.name=Click to Chat