##
## Test Suites
##

    modified.files.includes[relevant][microblogs-rule]=**

    relevant.rule.names=\
        microblogs-rule

    test.batch.names[relevant][microblogs-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][microblogs-rule]=\
        apps/microblogs/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][microblogs-rule]=\
        apps/microblogs/**/*Test.java

##
## Testray
##

    testray.main.component.name=Microblogs