##
## Test Suites
##

    modified.files.includes[relevant][knowledge-base-rule]=**

    relevant.rule.names=\
        knowledge-base-rule

    test.batch.names[relevant][knowledge-base-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][knowledge-base-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][knowledge-base-rule]=\
        apps/knowledge-base/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][knowledge-base-rule]=\
        apps/knowledge-base/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][knowledge-base-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Knowledge Base") OR \
            (testray.main.component.name ~ "Knowledge Base")\
        )

##
## Testray
##

    testray.main.component.name=Knowledge Base