##
## Test Suites
##

    modified.files.includes[relevant][invitation-rule]=**

    relevant.rule.names=\
        invitation-rule

    test.batch.names[relevant][invitation-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][invitation-rule]=\
        apps/invitation/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][invitation-rule]=\
        apps/invitation/**/*Test.java

##
## Testray
##

    testray.main.component.name=Invite Members