##
## Test Suites
##

    modified.files.includes[relevant][portal-language-override-web-rule]=**

    relevant.rule.names=\
        portal-language-override-web-rule

    test.batch.names[relevant][portal-language-override-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][portal-language-override-web-rule]=portal-language-override-web