##
## Test Suites
##

    modified.files.includes[relevant][digital-signature-rule]=**

    relevant.rule.names=\
        digital-signature-rule

    test.batch.names[relevant][digital-signature-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][digital-signature-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][digital-signature-rule]=\
        apps/digital-signature/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][digital-signature-rule]=\
        apps/digital-signature/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][digital-signature-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Digital Signature") OR \
            (testray.main.component.name ~ "Digital Signature")\
        )

##
## Testray
##

    testray.main.component.name=Digital Signature