##
## Test Suites
##

    modified.files.includes[relevant][my-subscriptions-rule]=**

    relevant.rule.names=\
        my-subscriptions-rule

    test.batch.names[relevant][my-subscriptions-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][my-subscriptions-rule]=\
        apps/my-subcriptions/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][my-subscriptions-rule]=\
        apps/my-subcriptions/**/*Test.java

##
## Testray
##

    testray.main.component.name=My Subscriptions