##
## Test Suites
##

    modified.files.includes[relevant][asset-display-page-api-rule]=**

    relevant.rule.names=\
        asset-display-page-api-rule

    test.batch.names[relevant][asset-display-page-api-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][asset-display-page-api-rule]=\
        **/asset-display-page-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-display-page-api-rule]=\
        **/asset-display-page-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Display Page Templates