##
## Test Suites
##

    modified.files.includes[relevant][analytics-settings-web-rule]=**

    relevant.rule.names=\
        analytics-settings-web-rule

    test.batch.names[relevant][analytics-settings-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][analytics-settings-web-rule]=analytics-settings-web