##
## Site Initializer Raylife D2C
##

    #site.initializer.raylife.d2c.paypal.client.id=
    #site.initializer.raylife.d2c.paypal.client.secret=
    #site.initializer.raylife.d2c.paypal.email=
    #site.initializer.raylife.d2c.paypal.password= 

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][site-initializer-raylife-d2c-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][site-initializer-raylife-d2c-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Site Initializer Raylife D2C") OR \
            (testray.main.component.name ~ "Site Initializer Raylife D2C")\
        )

##
## Test Suites
##

    modified.files.includes[relevant][site-initializer-raylife-d2c-rule]=**

    relevant.rule.names=\
        site-initializer-raylife-d2c-rule

    test.batch.names[relevant][site-initializer-raylife-d2c-rule]=\
        functional-tomcat90-mysql57