##
## Test Suites
##

    modified.files.includes[relevant][list-type-rule]=**

    relevant.rule.names=\
        list-type-rule

    test.batch.names[relevant][list-type-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][list-type-rule]=\
        apps/list-type/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][list-type-rule]=\
        apps/list-type/**/*Test.java

##
## Testray
##

    testray.main.component.name=Object