##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][announcements-web-rule]=announcements-web

##
## Test Suites
##

    modified.files.includes[relevant][announcements-web-rule]=**

    relevant.rule.names=\
        announcements-web-rule

    test.batch.names[relevant][announcements-web-rule]=\
        playwright-js-tomcat90-mysql57