##
## Test Suites
##

modified.files.includes[relevant][item-selector-taglib-rule]=**

relevant.rule.names=\
    item-selector-taglib-rule

test.batch.names[relevant][item-selector-taglib-rule]=\
    playwright-js-tomcat90-mysql57

#
# Relevant
#
playwright.test.project[playwright-js-tomcat90-mysql57][relevant][item-selector-taglib-rule]=item-selector-taglib