##
## Test Suites
##

    modified.files.includes[relevant][site-navigation-language-rule]=**

    relevant.rule.names=\
        site-navigation-language-rule

    test.batch.names[relevant][site-navigation-language-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][site-navigation-language-rule]=\
        apps/site-navigation/site-navigation-language/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][site-navigation-language-rule]=\
        apps/site-navigation/site-navigation-language/**/*Test.java

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][site-navigation-language-rule]=site-navigation-language-web

##
## Testray
##

    testray.main.component.name=Language Widget