##
## Test Suites
##

    modified.files.includes[relevant][oauth2-provider-rule]=**

    relevant.rule.names=\
        oauth2-provider-rule

    test.batch.names[relevant][oauth2-provider-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][oauth2-provider-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][oauth2-provider-rule]=\
        apps/oauth2-provider/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][oauth2-provider-rule]=\
        apps/oauth2-provider/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][oauth2-provider-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "OAuth 2") OR \
            (testray.main.component.name ~ "OAuth 2")\
        )

##
## Testray
##

    testray.main.component.name=OAuth 2