##
## Test Suites
##

    modified.files.includes[relevant][dynamic-data-mapping-form-web-rule]=**

    relevant.rule.names=\
        dynamic-data-mapping-form-web-rule

    test.batch.names[relevant][dynamic-data-mapping-form-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][dynamic-data-mapping-form-web-rule]=dynamic-data-mapping-form-web

##
## Testray
##

    testray.main.component.name=Dynamic Data Mapping