##
## Test Suites
##

    modified.files.includes[relevant][osb-faro-web-rule]=**

    relevant.rule.names=\
        osb-faro-web-rule

    test.batch.names[relevant][osb-faro-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][osb-faro-web-rule]=osb-faro-web