##
## Test Suites
##

    modified.files.includes[relevant][sass-compiler-dart-rule]=**

    relevant.rule.names=\
        sass-compiler-dart-rule

    test.batch.names[relevant][sass-compiler-dart-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][sass-compiler-dart-rule]=\
        util/sass-compiler-dart/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][sass-compiler-dart-rule]=\
        util/sass-compiler-dart/**/*Test.java