##
## Test Suites
##

    modified.files.includes[relevant][contacts-rule]=**

    relevant.rule.names=\
        contacts-rule

    test.batch.names[relevant][contacts-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][contacts-rule]=\
        apps/contacts/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][contacts-rule]=\
        apps/contacts/**/*Test.java

##
## Testray
##

    testray.main.component.name=Contacts Center