##
## Test Suites
##

    modified.files.includes[relevant][subscription-rule]=**

    relevant.rule.names=\
        subscription-rule

    test.batch.names[relevant][subscription-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][subscription-rule]=\
        apps/subscription/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][subscription-rule]=\
        apps/subscription/**/*Test.java

##
## Testray
##

    testray.main.component.name=My Subscriptions