##
## Test Suites
##

    modified.files.includes[relevant][server-rule]=**

    relevant.rule.names=\
        server-rule

    test.batch.names[relevant][server-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][server-rule]=\
        apps/server/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][server-rule]=\
        apps/server/**/*Test.java

##
## Testray
##

    testray.main.component.name=Server Administration