##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][journal-web-rule]=journal-web

##
## Test Suites
##

    modified.files.includes[relevant][journal-web-rule]=**

    relevant.rule.names=\
        journal-web-rule

    test.batch.names[relevant][journal-web-rule]=\
        playwright-js-tomcat90-mysql57