##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][message-boards-web-rule]=message-boards-web

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][message-boards-web-rule]=\
        (testray.component.names == "Message Boards") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    modified.files.includes[relevant][message-boards-web-rule]=**

    relevant.rule.names=\
        message-boards-web-rule

    test.batch.names[relevant][message-boards-web-rule]=\
        functional-upgrade-tomcat90-mysql57,\
        playwright-js-tomcat90-mysql57

##
## Testray
##

    testray.main.component.name=Message Boards