##
## Test Suites
##

    modified.files.includes[relevant][talend-rule]=**

    relevant.rule.names=\
        talend-rule

    test.batch.names[relevant][talend-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][talend-rule]=\
        core/talend/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][talend-rule]=\
        core/talend/**/*Test.java