##
## Test Suites
##

    modified.files.includes[relevant][view-count-rule]=**

    relevant.rule.names=\
        view-count-rule

    test.batch.names[relevant][view-count-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][view-count-rule]=\
        apps/view-count/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][view-count-rule]=\
        apps/view-count/**/*Test.java

##
## Testray
##

    testray.main.component.name=Util