##
## Relevant
##

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][document-library-google-docs-rule]=\
        apps/document-library-google-docs/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][document-library-google-docs-rule]=\
        apps/document-library-google-docs/**/*Test.java

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][document-library-google-docs-rule]=\
        (testray.component.names == "External Document Repositories") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    modified.files.includes[relevant][document-library-google-docs-rule]=**

    relevant.rule.names=\
        document-library-google-docs-rule

    test.batch.names[relevant][document-library-google-docs-rule]=\
        functional-upgrade-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

##
## Testray
##

    testray.main.component.name=External Document Repositories