##
## Test Suites
##

    modified.files.includes[relevant][imageio-plugins-rule]=**

    relevant.rule.names=\
        imageio-plugins-rule

    test.batch.names[relevant][imageio-plugins-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][imageio-plugins-rule]=\
        apps/imageio-plugins/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][imageio-plugins-rule]=\
        apps/imageio-plugins/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services