##
## Test Suites
##

    modified.files.includes[relevant][commerce-avalara-rule]=**

    relevant.rule.names=\
        commerce-avalara-rule

    test.batch.names[relevant][commerce-avalara-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][commerce-avalara-rule]=\
        dxp/apps/commerce-avalara/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][commerce-avalara-rule]=\
        dxp/apps/commerce-avalara/**/*Test.java

##
## Testray
##

    testray.main.component.name=Commerce