##
## Test Suites
##

    modified.files.includes[relevant][client-extension-web-rule]=**

    relevant.rule.names=\
        client-extension-web-rule

    test.batch.names[relevant][client-extension-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][client-extension-web-rule]=client-extension-web