##
## Test Suites
##

    modified.files.includes[relevant][notification-rule]=**

    relevant.rule.names=\
        notification-rule

    test.batch.names[relevant][notification-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][notification-rule]=\
        apps/notification/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][notification-rule]=\
        apps/notification/**/*Test.java

##
## Testray
##

    testray.main.component.name=Notifications Framework