##
## Test Suites
##

    modified.files.includes[relevant][frontend-data-set-web-rule]=**

    relevant.rule.names=\
        frontend-data-set-web-rule

    test.batch.names[relevant][frontend-data-set-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][frontend-data-set-web-rule]=frontend-data-set-web