##
## Test Suites
##

    modified.files.includes[relevant][user-associated-data-rule]=**

    relevant.rule.names=\
        user-associated-data-rule

    test.batch.names[relevant][user-associated-data-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][user-associated-data-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][user-associated-data-rule]=\
        apps/user-associated-data/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][user-associated-data-rule]=\
        apps/user-associated-data/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][user-associated-data-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Personal Data") OR \
            (testray.main.component.name ~ "Personal Data")\
        )

##
## Testray
##

    testray.main.component.name=Personal Data