##
## Playwright
##

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][object-rule]=object

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][object-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][object-rule]=\
        apps/object/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][object-rule]=\
        apps/object/**/*Test.java

    test.batch.class.names.includes[relevant][object-rule]=\
        **/headless-builder/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][object-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names == "Object") OR \
            (testray.main.component.name == "Object")\
        )

##
## Test Suites
##

    modified.files.includes[relevant][object-rule]=**

    relevant.rule.names=\
        object-rule

    test.batch.names[relevant][object-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit,\
        playwright-js-tomcat90-mysql57

##
## Testray
##

    testray.main.component.name=Object