##
## Test Suites
##

    modified.files.includes[relevant][reading-time-rule]=**

    relevant.rule.names=\
        reading-time-rule

    test.batch.names[relevant][reading-time-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][reading-time-rule]=\
        apps/reading-time/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][reading-time-rule]=\
        apps/reading-time/**/*Test.java

##
## Testray
##

    testray.main.component.name=Blogs