##
## Test Suites
##

    modified.files.includes[relevant][normalizer-rule]=**

    relevant.rule.names=\
        normalizer-rule

    test.batch.names[relevant][normalizer-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][normalizer-rule]=\
        apps/normalizer/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][normalizer-rule]=\
        apps/normalizer/**/*Test.java