##
## Test Suites
##

    modified.files.includes[relevant][search-experiences-web-rule]=**

    relevant.rule.names=\
        search-experiences-web-rule

    test.batch.names[relevant][search-experiences-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][search-experiences-web-rule]=search-experiences-web