##
## Test Suites
##

    modified.files.includes[relevant][company-rule]=**

    relevant.rule.names=\
        company-rule

    test.batch.names[relevant][company-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][company-rule]=\
        apps/company/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][company-rule]=\
        apps/company/**/*Test.java

##
## Testray
##

    testray.main.component.name=Virtual Instances