##
## Test Suites
##

    modified.files.includes[relevant][users-admin-web-rule]=**

    relevant.rule.names=\
        users-admin-web-rule

    test.batch.names[relevant][users-admin-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][users-admin-web-rule]=users-admin-web