##
## Test Suites
##

    modified.files.includes[relevant][change-tracking-web-rule]=**

    relevant.rule.names=\
        change-tracking-web-rule

    test.batch.names[relevant][change-tracking-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][change-tracking-web-rule]=change-tracking-web