##
## Test Suites
##

    modified.files.includes[relevant][google-places-rule]=**

    relevant.rule.names=\
        google-places-rule

    test.batch.names[relevant][google-places-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][google-places-rule]=\
        apps/google-places/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][google-places-rule]=\
        apps/google-places/**/*Test.java

##
## Testray
##

    testray.main.component.name=Forms