##
## Test Suites
##

    modified.files.includes[relevant][hello-velocity-rule]=**

    relevant.rule.names=\
        hello-velocity-rule

    test.batch.names[relevant][hello-velocity-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][hello-velocity-rule]=\
        apps/hello-velocity/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][hello-velocity-rule]=\
        apps/hello-velocity/**/*Test.java

##
## Testray
##

    testray.main.component.name=Templates Engine