##
## Test Suites
##

    modified.files.includes[relevant][account-admin-web-rule]=**

    relevant.rule.names=\
        account-admin-web-rule

    test.batch.names[relevant][account-admin-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][account-admin-web-rule]=account-admin-web