##
## Test Suites
##

    modified.files.includes[relevant][depot-rule]=**

    relevant.rule.names=\
        depot-rule

    test.batch.names[relevant][depot-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][depot-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][depot-rule]=\
        apps/depot/**/*Test.java,\
        apps/portal-security/portal-security-permission-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][depot-rule]=\
        apps/depot/**/*Test.java,\
        apps/portal-security/portal-security-permission-test/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][depot-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Depot") OR \
            (testray.main.component.name ~ "Depot")\
        )

##
## Testray
##

    testray.main.component.name=Depot