##
## Test Suites
##

    modified.files.includes[relevant][document-library-opener-rule]=**

    relevant.rule.names=\
        document-library-opener-rule

    test.batch.names[relevant][document-library-opener-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][document-library-opener-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][document-library-opener-rule]=\
        apps/document-library-opener/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][document-library-opener-rule]=\
        apps/document-library-opener/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][document-library-opener-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Online Editing")

##
## Testray
##

    testray.main.component.name=External Document Repositories