##
## Test Suites
##

    modified.files.includes[relevant][scim-configuration-web-rule]=**

    relevant.rule.names=\
        scim-configuration-web-rule

    test.batch.names[relevant][scim-configuration-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant]=scim-configuration-web
    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][scim-configuration-web-rule]=scim-configuration-web