##
## Test Suites
##

    modified.files.includes[relevant][upload-rule]=**

    relevant.rule.names=\
        upload-rule

    test.batch.names[relevant][upload-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][upload-rule]=\
        apps/upload/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][upload-rule]=\
        apps/upload/**/*Test.java

##
## Testray
##

    testray.main.component.name=Item Selector