##
## Test Suites
##

    modified.files.includes[relevant][pmd-rule]=**

    relevant.rule.names=\
        pmd-rule

    test.batch.names[relevant][pmd-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][pmd-rule]=\
        util/pmd/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][pmd-rule]=\
        util/pmd/**/*Test.java