##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][document-library-web-rule]=document-library-web

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][document-library-web-rule]=\
        (testray.component.names == "Document Management") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    modified.files.includes[relevant][document-library-web-rule]=**

    relevant.rule.names=\
        document-library-web-rule

    test.batch.names[relevant][document-library-web-rule]=\
        functional-upgrade-tomcat90-mysql57,\
        playwright-js-tomcat90-mysql57

##
## Testray
##

    testray.main.component.name=Document Management