##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][knowledge-base-web-rule]=knowledge-base-web

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][knowledge-base-web-rule]=\
        (testray.component.names == "Knowledge Base") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    modified.files.includes[relevant][knowledge-base-web-rule]=**

    relevant.rule.names=\
        knowledge-base-web-rule

    test.batch.names[relevant][knowledge-base-web-rule]=\
        functional-upgrade-tomcat90-mysql57,\
        playwright-js-tomcat90-mysql57

##
## Testray
##

    testray.main.component.name=Knowledge Base