##
## Test Suites
##

    modified.files.includes[relevant][counter-rule]=**

    relevant.rule.names=\
        counter-rule

    test.batch.names[relevant][counter-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][counter-rule]=\
        apps/counter/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][counter-rule]=\
        apps/counter/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services