##
## Test Suites
##

    modified.files.includes[relevant][style-book-web-rule]=**

    relevant.rule.names=\
        style-book-web-rule

    test.batch.names[relevant][style-book-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][style-book-web-rule]=style-book-web