##
## Test Suites
##

    modified.files.includes[relevant][locked-items-web-rule]=**

    relevant.rule.names=\
        locked-items-web-rule

    test.batch.names[relevant][locked-items-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][locked-items-web-rule]=locked-items-web