##
## Test Suites
##

    modified.files.includes[relevant][comment-rule]=**

    relevant.rule.names=\
        comment-rule

    test.batch.names[relevant][comment-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][comment-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][comment-rule]=\
        apps/comment/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][comment-rule]=\
        apps/comment/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][comment-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Comment") OR \
            (testray.main.component.name ~ "Comment")\
        )

##
## Testray
##

    testray.main.component.name=Comment