##
## Test Suites
##

    modified.files.includes[relevant][calendar-web-rule]=**

    relevant.rule.names=\
        calendar-web-rule

    test.batch.names[relevant][calendar-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][calendar-web-rule]=calendar-web