##
## Test Suites
##

    modified.files.includes[relevant][json-storage-rule]=**

    relevant.rule.names=\
        json-storage-rule

    test.batch.names[relevant][json-storage-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][json-storage-rule]=\
        apps/json-storage/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][json-storage-rule]=\
        apps/json-storage/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services