##
## Test Suites
##

    modified.files.includes[relevant][questions-rule]=**

    relevant.rule.names=\
        questions-rule

    test.batch.names[relevant][questions-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][questions-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][questions-rule]=\
        apps/message-boards/**/*Test.java,\
        apps/questions/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][questions-rule]=\
        apps/message-boards/**/*Test.java,\
        apps/questions/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][questions-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Questions")

##
## Testray
##

    testray.main.component.name=Questions