##
## Test Suites
##

    modified.files.includes[relevant][login-web-rule]=**

    relevant.rule.names=\
        login-web-rule

    test.batch.names[relevant][login-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][login-web-rule]=login-web