##
## Test Suites
##

    modified.files.includes[relevant][saved-content-rule]=**

    relevant.rule.names=\
        saved-content-rule

    test.batch.names[relevant][saved-content-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][saved-content-rule]=\
        apps/saved-content/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][saved-content-rule]=\
        apps/saved-content/**/*Test.java

##
## Testray
##

    testray.main.component.name=Saved Content