##
## Test Suites
##

    modified.files.includes[relevant][learn-rule]=**

    relevant.rule.names=\
        learn-rule

    test.batch.names[relevant][learn-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][learn-rule]=\
        apps/learn/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][learn-rule]=\
        apps/learn/**/*Test.java

##
## Testray
##

    testray.main.component.name=Setup Wizard