##
## Test Suites
##

    modified.files.includes[relevant][shared-dependencies-rule]=**

    relevant.rule.names=\
        shared-dependencies-rule

    test.batch.names[relevant][shared-dependencies-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][shared-dependencies-rule]=\
        apps/shared-dependencies/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][shared-dependencies-rule]=\
        apps/shared-dependencies/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services