##
## Test Suites
##

    modified.files.includes[relevant][connected-app-rule]=**

    relevant.rule.names=\
        connected-app-rule

    test.batch.names[relevant][connected-app-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][connected-app-rule]=\
        apps/connected-app/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][connected-app-rule]=\
        apps/connected-app/**/*Test.java

##
## Testray
##

    testray.main.component.name=Document Management