##
## Test Suites
##

    modified.files.includes[relevant][dynamic-data-mapping-rule]=**

    relevant.rule.names=\
        dynamic-data-mapping-rule

    test.batch.names[relevant][dynamic-data-mapping-rule]=\
        functional-tomcat90-mysql57,\
        functional-upgrade-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][dynamic-data-mapping-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][dynamic-data-mapping-rule]=\
        apps/document-library/document-library-test/**/*Test.java,\
        apps/dynamic-data-mapping/**/*Test.java,\
        apps/journal/journal-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][dynamic-data-mapping-rule]=\
        apps/document-library/document-library-test/**/*Test.java,\
        apps/dynamic-data-mapping/**/*Test.java,\
        apps/journal/journal-test/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][dynamic-data-mapping-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Forms") OR \
            (testray.component.names ~ "Site Templates") OR \
            (testray.main.component.name == "Forms") OR \
            (testray.main.component.name ~ "Content Management Headless")\
        )

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][dynamic-data-mapping-rule]=\
        (\
            (data.archive.type != "data-archive-calendar") AND \
            (portal.acceptance == true) AND \
            (portal.release != "false") AND \
            (testray.main.component.name == "Upgrades Forms")\
        ) OR \
        (\
            (portal.acceptance == true) AND \
            (testray.main.component.name ~ "Upgrades Content Management")\
        )

##
## Testray
##

    testray.main.component.name=Dynamic Data Mapping