##
## Test Suites
##

    modified.files.includes[relevant][configuration-admin-web-rule]=**

    relevant.rule.names=\
        configuration-admin-web-rule

    test.batch.names[relevant][configuration-admin-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][configuration-admin-web-rule]=configuration-admin-web