##
## Test Suites
##

    modified.files.includes[relevant][staging-rule]=**

    relevant.rule.names=\
        staging-rule

    test.batch.names[relevant][staging-rule]=\
        functional-tomcat90-mysql57,\
        functional-upgrade-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][staging-rule]=\
        **/asset-test/**/AssetSearcherStagingTest.java,\
        **/src/testIntegration/**/calendar/**/*Test.java,\
        **/src/testIntegration/**/staging/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][staging-rule]=\
        apps/staging/**/*Test.java

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][staging-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][staging-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.main.component.name ~ "Export/Import") OR \
            (testray.main.component.name ~ "Site Templates") OR \
            (testray.main.component.name ~ "Staging")\
        )

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][staging-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Upgrades Staging")

##
## Testray
##

    testray.main.component.name=Staging