##
## Test Suites
##

    modified.files.includes[relevant][license-manager-rule]=**

    relevant.rule.names=\
        license-manager-rule

    test.batch.names[relevant][license-manager-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][license-manager-rule]=\
        apps/license-manager/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][license-manager-rule]=\
        apps/license-manager/**/*Test.java

##
## Testray
##

    testray.main.component.name=License