##
## Test Suites
##

    modified.files.includes[relevant][source-formatter-rule]=**

    relevant.rule.names=\
        source-formatter-rule

    test.batch.names[relevant][source-formatter-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][source-formatter-rule]=\
        util/source-formatter/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][source-formatter-rule]=\
        util/source-formatter/**/*Test.java

##
## Testray
##

    testray.main.component.name=Source Formatter