##
## Test Suites
##

    modified.files.includes[relevant][address-rule]=**

    relevant.rule.names=\
        address-rule

    test.batch.names[relevant][address-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][address-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][address-rule]=\
        apps/address/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][address-rule]=\
        apps/address/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][address-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Address") OR \
            (testray.main.component.name ~ "Address")\
        )

##
## Testray
##

    testray.main.component.name=Address