##
## Test Suites
##

    modified.files.includes[relevant][commerce-rule]=**

    relevant.rule.names=\
        commerce-rule

    test.batch.names[relevant][commerce-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit,\
        playwright-js-tomcat90-mysql57

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][commerce-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][commerce-rule]=\
        dxp/apps/commerce/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][commerce-rule]=\
        dxp/apps/commerce/**/*Test.java

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][commerce-rule]=commerce

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][commerce-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Commerce")

##
## Testray
##

    testray.main.component.name=Commerce