##
## Test Suites
##

    modified.files.includes[relevant][notifications-rule]=**

    relevant.rule.names=\
        notifications-rule

    test.batch.names[relevant][notifications-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][notifications-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][notifications-rule]=\
        apps/notifications/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][notifications-rule]=\
        apps/notifications/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][notifications-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Notifications")

##
## Testray
##

    testray.main.component.name=Notifications